In [1]:
>>> # Import the flywire module
>>> from fafbseg import flywire

>>> # We will use the public dataset for this tutorial
>>> flywire.set_default_dataset("public")

Default dataset set to "public".


In [5]:
>>> # Check which materilizations are available
>>> flywire.get_materialization_versions()

time_stamp          expires_on  is_merged            datastack  \
0 2023-03-21 08:10:00 2121-11-10 07:10:00       True  flywire_fafb_public   

   version  valid     status   id  
0      630   True  AVAILABLE  718

In [22]:
>>> # Fetch the root IDs at given x/y/z coordinate(s)
>>> roots = flywire.locs_to_segments([[75350, 60162, 3162]])
>>> roots

array([720575940631680813])

In [23]:
>>> # We can also specify a timstamp matching the materialization version
>>> # which will be useful later when more versions are available
>>> roots = flywire.locs_to_segments([[75350, 60162, 3162]], timestamp='mat_630')
>>> roots

array([720575940631680813])

In [24]:
>>> # Check if root IDs are outdated (i.e. have more recent edits)
>>> flywire.is_latest_root([720575940625431866, 720575940621835755])

array([ True, False])

In [25]:
>>> # Likewise, we can ask if they were current at a given materialization
>>> flywire.is_latest_root([720575940625431866, 720575940621835755],
...                        timestamp='mat_630')

array([ True, False])

In [26]:
>>> updated = flywire.update_ids(
...     [720575940621835755, 720575940608788840, 720575940628913983]
... )
>>> updated

Updating:   0%|          | 0/3 [00:00<?, ?it/s]

old_id              new_id  confidence  changed
0  720575940621835755  720575940636873791        0.99     True
1  720575940608788840  720575940636873791        1.00     True
2  720575940628913983  720575940636873791        0.94     True

In [27]:
>>> edits = flywire.get_edit_history(720575940625431866)
>>> edits.head()

after_root_ids                           before_root_ids  is_merge  \
2  [720575940625153661]                      [720575940613909190]     False   
3  [720575940626449738]  [720575940617774213, 720575940625153661]      True   
4  [720575940604045489]                      [720575940618706267]     False   
5  [720575940626907179]  [720575940604045489, 720575940626449738]      True   
6  [720575940604045745]  [720575940626907179, 720575940626995629]      True   

   operation_id             segment               timestamp  \
2        546853  720575940625431866 2021-08-19 09:10:18.090   
3        546854  720575940625431866 2021-08-19 09:10:36.280   
4        546855  720575940625431866 2021-08-19 09:11:20.009   
5        546856  720575940625431866 2021-08-19 09:11:34.230   
6        546857  720575940625431866 2021-08-19 09:12:06.042   

    user_affiliation user_id   user_name  
2  Greg Jefferis Lab     957  Varun Sane  
3  Greg Jefferis Lab     957  Varun Sane  
4  Greg Jefferis Lab     957  Varun Sane  
5  Greg Jefferis Lab     957  Varun Sane  
6  Greg Jefferis Lab     957  Varun Sane